version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personalwebsite-app
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - "ConnectionStrings__DefaultConnection=Data Source=/app/data/personalwebsite.db"
    volumes:
      - app-data:/app/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6060/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - "6060:6060"

networks:
  app-network:
    driver: bridge

volumes:
  app-data:
    driver: local
  caddy-data:
    driver: local
  caddy-config:
    driver: local